function fileHandler_html4(b,g){if("upload"==KUPLOADTOP.G_CURRKUPLOADER._config.mode){var h=[],a=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileCount,f=!0,c=[],m={file:b,name:getFileName(g,!1),size:"",type:"",lastModifiedDate:""};c.push(m);var m=[],e=KUPLOADTOP.G_CURRKUPLOADER.frameWin.getTotalFileCount(),d=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.duplication,n=0,l=!1;"0"==KUPLOADTOP.G_CURRKUPLOADER._config.allowDuplicationFile&&(l=sameFileCheck(c[0]));if(l)"0"==d&&alert(c[0].name+" "+
RAONKUpload_Lang.message_duplication_file);else{var d=!1,l=KUPLOADTOP.G_CURRKUPLOADER._config.extension,p=l.extArr.length;if(0<p){var v=l.allowOrLimit;if("1"==v){for(var u=getExtension(c[0].name),q=0;q<p;q++)if(("***"==l.extArr[q]?"":l.extArr[q])==u){d=!0;break}d||m.push(""==u?'" "':u)}else for(u=getExtension(c[0].name),q=0;q<p;q++)if(("***"==l.extArr[q]?"":l.extArr[q])==u){d=!1;m.push(""==u?'" "':u);break}else d=!0}else d=!0;calcTotalSize();l=TOTALREALFILENUM;if(0!=a&&l+1>a){e=RAONKUpload_Lang.message_limit_num;
e=e.replace("{0}",a);alert(e);return}if(d){var w=a="";document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID)&&(w=document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value);null==g&&(g="");(a=g)&&(a=KUPLOADTOP.RAONKUPLOAD.util.trim(a));if("undefined"==typeof a||null==a)a="undefined"==typeof filePathSplit[0]||null==filePathSplit[0]?"":filePathSplit[0].substring(0,filePathSplit[0].lastIndexOf(KUPLOADTOP.RAONKUPLOAD.UserAgent.osSeparator)+1)+c[0].name;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAddEvent)try{var k=
c[0].file,r={strName:c[0].name,nSize:c[0].size,nIndex:e+n,strPath:a,dropZoneId:"",objFile:k,isFolder:"1"==c[0].isFolder?!0:!1,strPreviewUrl:""},f="function"==typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.beforeAddFile?KUPLOADTOP.G_CURRKUPLOADER._config.event.beforeAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,r):KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_BeforeAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,r);!1!==f&&(f=!0)}catch(x){}if(f){f=c[0].type;if(null==f||void 0==f||""==f)f="application/octet-stream";a={file:c[0].file,
guid:"",fileIdx:"",webPath:"",originName:c[0].name,fileSize:c[0].size,uploadName:"",uploadPath:"",logicalPath:"",status:"ready",fileExt:"",isDelete:"n",isWebFile:"n",localPath:a,customValue:"",responseCustomValue:"",headerEx:"",lastModifiedDate:c[0].lastModifiedDate,mimeType:f};RESULTFILELIST.push(a);a.isFolder="0";addFileList(a);if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEvent)try{calcTotalSize(),k=c[0].file,r={strName:c[0].name,nSize:c[0].size,nIndex:e+n,strPath:a.localPath,dropZoneId:"",
objFile:k,isFolder:"1"==c[0].isFolder?!0:!1,strPreviewUrl:""},h.push(r),"function"==typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddFile?KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,r):KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,r)}catch(y){}n++;c=document.getElementById("files_container");KUPLOADTOP.G_CURRKUPLOADER.TagID=KUPLOADTOP.RAONKUPLOAD.util.makeGuidTagName();k=document.createElement("form");k.setAttribute("id",
"form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);k.setAttribute("method","post");k.setAttribute("enctype","multipart/form-data");k.setAttribute("encoding","multipart/form-data");e=document.createElement("span");e.className="input_image_add";e.innerHTML=RAONKUpload_Lang.btn_add;""!=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor&&(e.style.background=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor);""!=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor&&(e.style.color=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor);
var t=document.createElement("input");t.setAttribute("id","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);t.setAttribute("name","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);t.setAttribute("type","file");KUPLOADTOP.RAONKUPLOAD.util.addEvent(t,"change",function(){fileHandler_html4(t,t.value)});KUPLOADTOP.RAONKUPLOAD.util.addEvent(t,"blur",function(){focusHandler(t)});a=document.createElement("input");a.setAttribute("id","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);a.setAttribute("name","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);
a.setAttribute("type","hidden");a.setAttribute("value","0");k.appendChild(e);k.appendChild(t);k.appendChild(a);e=document.createElement("div");e.appendChild(k);c.appendChild(e);e.previousSibling&&(e.previousSibling.style.display="none",e.previousSibling.childNodes[0].childNodes[1].tabIndex="-1")}}}displayTotalSizeAndNum();c=m.length;if(0<c){e="";k=KUPLOADTOP.G_CURRKUPLOADER._config.extension.extArr;e=k.length;for(a=0;a<e;a++)"***"==k[a]&&(k[a]='" "');"1"==v?1<c?(e=RAONKUpload_Lang.message_not_allow_exts,
e=e.replace("{0}",c),e=e.replace("{1}",k)):(e=RAONKUpload_Lang.message_not_allow_ext,e=e.replace("{0}",k),e=e.replace("{1}",m[0])):1<c?(e=RAONKUpload_Lang.message_not_limit_exts,e=e.replace("{0}",c),e=e.replace("{1}",k)):(e=RAONKUpload_Lang.message_not_limit_ext,e=e.replace("{0}",k),e=e.replace("{1}",m[0]));alert(e)}"1"==KUPLOADTOP.G_CURRKUPLOADER._config.use_file_sort&&"1"==KUPLOADTOP.G_CURRKUPLOADER._config.auto_sort&&"1"!=KUPLOADTOP.G_CURRKUPLOADER._config.sort_field&&sortTotalFileList(KUPLOADTOP.G_CURRKUPLOADER._config.sort_field,
KUPLOADTOP.G_CURRKUPLOADER._config.sort_ascdesc);calcTotalSize();fileListSortIconReset();setFileListBorder();setListvalue();setLargeFileAllList();1==w&&(document.getElementById("file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).focus(),document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundImage="url("+KUPLOADTOP.G_CURRKUPLOADER._config.webPath.image+"img_bt_line.png)",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundRepeat=
"no-repeat",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionY="2px",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionX="1px",document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value="1",G_FileHandlerControl=0);"thumbs"==KUPLOADTOP.G_CURRKUPLOADER._config.views&&thumbsViewWithCanvas();if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEndTimeEvent&&0<n)try{r={arrFileList:h},
"function"==typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddAllFile?KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID,r):KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID,r)}catch(z){}}}
function processUploadHtml4(){if(!KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){var b=getDialogDocument();0==upload_complete_count&&(G_UploadStartTime=(new Date).getTime()/1E3);var g=document.getElementById("files_container").getElementsByTagName("form"),h=0;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile)for(var a=0;a<uploaders[upload_complete_count];a++)RESULTFILELIST[a].file&&"complete"==RESULTFILELIST[a].status&&h++;g=g[upload_complete_count+h];h=document.charset;document.charset="utf-8";
var f=upload_complete_count.toString();f==(uploaders.length-1).toString()&&(f+="z");RESULTFILELIST[uploaders[upload_complete_count]].guid=KUPLOADTOP.RAONKUPLOAD.util.makeGuid();var c=g.getElementsByTagName("input"),m=c[0],c=c[1];g.removeChild(c);for(var e=0,d=RESULTFILELIST.length,a=0;a<uploaders[upload_complete_count];a++)"n"==RESULTFILELIST[a].isDelete&&(e+=parseInt(RESULTFILELIST[a].fileSize,10));for(a=uploaders[upload_complete_count]+1;a<d;a++)"y"==RESULTFILELIST[a].isWebFile&&(e+=parseInt(RESULTFILELIST[a].fileSize,
10));d=""+("kc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c02"+KUPLOADTOP.RAONKSolution.Agent.vertical);d+="k01"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].guid+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k14"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].originName+
KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k15"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k16"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRuleEx+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k17"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.folderNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k20"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
f+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k21"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].customValue+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k22"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k23"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="k24"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.allowedZeroFileSize+KUPLOADTOP.RAONKSolution.Agent.vertical;
"1"==KUPLOADTOP.G_CURRKUPLOADER._config.security.fileExtensionDetector&&(d+="k29"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical);a=KUPLOADTOP.G_CURRKUPLOADER._config.maxOneFileSize;0!=a&&(d+="k40"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical);a=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileSize;0!=a&&(d+="k41"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical,d+="k42"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
e+KUPLOADTOP.RAONKSolution.Agent.vertical);KUPLOADTOP.G_CURRKUPLOADER._config.cloudInfo.Use&&"2"==KUPLOADTOP.G_CURRKUPLOADER._config.cloudInfo.Use&&(d+="k46"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.cloudInfo.Use+KUPLOADTOP.RAONKSolution.Agent.vertical);a=document.createElement("input");a.type="hidden";e=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(d);a.name=e.name;a.value=e.value;g.insertBefore(a,m);KUPLOADTOP.RAONKUPLOAD.util.setCSRFHiddenInput(g,KUPLOADTOP.G_CURRKUPLOADER._config.addCSRFToken,
document);f=G_FormData.length;e=[];for(d=0;d<f;d++){var n=G_FormData[d].form_value,n="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(n).value:encodeURIComponent(n),l=document.createElement("input");l.type="hidden";l.name=G_FormData[d].form_name;l.value=n;g.insertBefore(l,m);e.push(l)}var p=document.createElement("div"),d=KUPLOADTOP.RAONKUPLOAD.util.getDefaultIframeSrc();p.innerHTML='<iframe name="uploadframe" id="uploadframe" style="display:none;" src="'+
d+'"></iframe>';p.style.display="none";document.body.appendChild(p);KUPLOADTOP.RAONKUPLOAD.util.addEvent(p.firstChild,"load",function(){p.firstChild.contentWindow.postMessage("check","*");if(0==KUPLOADTOP.G_CURRKUPLOADER._config.isCrossDomain){KUPLOADTOP.RAONKUPLOAD.util.removeEvent(window,"message",v);document.body.removeChild(p);var a=p.firstChild.contentWindow.document.body.innerHTML,a=KUPLOADTOP.RAONKUPLOAD.util.trim(a);uploadEnd_html4(a)}},!0);if(window.postMessage){var v=function(a){KUPLOADTOP.RAONKUPLOAD.util.removeEvent(window,
"message",v);document.body.removeChild(p);a=KUPLOADTOP.RAONKUPLOAD.util.trim(a.data);uploadEnd_html4(a)};KUPLOADTOP.RAONKUPLOAD.util.addEvent(window,"message",v)}g.setAttribute("target","uploadframe");g.setAttribute("action",KUPLOADTOP.G_CURRKUPLOADER._config.handlerUrl);b.getElementById("RAON_K_UP_current_upload_file_name").innerHTML=" "+RESULTFILELIST[uploaders[upload_complete_count]].originName;g.submit();document.charset=h;g.removeChild(a);for(a=f-1;0<=a;a--)g.removeChild(e[a]);g.insertBefore(c,
m.nextSibling);uploadProgress_html4(upload_complete_count,TOTALUPLOADNUM,50)}}
function uploadEnd_html4(b){var g=getDialogDocument(),h=function(a,c){var b=getUploadedFileListObj();try{if(b={strType:"upload",strCode:a,strMessage:c,arrUploadedFileList:b},"function"==typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.onError)KUPLOADTOP.G_CURRKUPLOADER._config.event.onError(KUPLOADTOP.G_CURRKUPLOADER.ID,b);else"function"!==typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError&&alert("Error Code : "+b.strCode+"\nError Message : "+b.strMessage),KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError(KUPLOADTOP.G_CURRKUPLOADER.ID,
b)}catch(d){}if(1==G_MultiTranferCheck)G_MultiTranferCheck=4;else try{"0"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile&&fileListReset()}catch(e){}clearInterval(G_IntervalObj);PREVIOUSUPLOADEDSIZE=0;g.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=
!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()};b=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(b);if(0==b.indexOf("[OK]"))if(b=b.replace("[OK]",""),b=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(b),"C012|response data decrypt error"==b)b=b.split("|"),h(b[0],b[1]);else{h=b.split(KUPLOADTOP.RAONKSolution.Agent.formfeed);b=h[0];var a="",f="",c=b.indexOf("::");-1<c&&(a=b.substring(0,c),b=b.substring(c+2,b.length));c=b.indexOf(":");
-1<c&&(f=b.substring(0,c),b=b.substring(c+1,b.length));c="";c=b.length;"|"==b.substring(c-1,c)?(b=b.substring(0,c-1),c=getFileName(b,!1),b=b.substring(0,b.lastIndexOf("/"+c))):c=getFileName(b,!1);RESULTFILELIST[uploaders[upload_complete_count]].uploadName=c;RESULTFILELIST[uploaders[upload_complete_count]].uploadPath=b;RESULTFILELIST[uploaders[upload_complete_count]].fileSize=h[2];RESULTFILELIST[uploaders[upload_complete_count]].status="complete";RESULTFILELIST[uploaders[upload_complete_count]].logicalPath=
"";RESULTFILELIST[uploaders[upload_complete_count]].responseCustomValue=h[1];""!=f&&(RESULTFILELIST[uploaders[upload_complete_count]].originName=f);RESULTFILELIST[uploaders[upload_complete_count]].hashValue=a;KUPLOADTOP.G_CURRKUPLOADER.uploadedTaskId="";KUPLOADTOP.G_CURRKUPLOADER.uploadedSize=0;PREVIOUSUPLOADEDSIZE+=parseInt(h[2],10);clearInterval(G_IntervalObj);uploadProgressComplete_html4(KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(h[2]));upload_complete_count++;if(KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){if("1"==
KUPLOADTOP.G_CURRKUPLOADER._config.useUploadingCancelEvent){h={strType:"upload",bAutoTransferFlag:!1,arrAllFileList:null,arrUploadedFileList:getUploadedFileListObj()};try{"function"==typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.uploadingCancel?KUPLOADTOP.G_CURRKUPLOADER._config.event.uploadingCancel(KUPLOADTOP.G_CURRKUPLOADER.ID,h):KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_UploadingCancel(KUPLOADTOP.G_CURRKUPLOADER.ID,h)}catch(m){}}if(1==G_MultiTranferCheck)G_MultiTranferCheck=3;else try{"0"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile&&
fileListReset()}catch(e){}PREVIOUSUPLOADEDSIZE=0;g.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()}else upload_complete_count==
TOTALUPLOADNUM?(PREVIOUSUPLOADEDSIZE=0,g.getElementById("RAON_K_UP_upload_size").innerHTML="-",totalUploadComplete(),0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1)):(h=uploaders.indexOf(uploaders[upload_complete_count]),adjustUploadFileListScroll(h,upload_complete_count,TOTALUPLOADNUM),processUploadHtml4())}else if(0==b.indexOf("[FAIL]")){b=b.replace("[FAIL]","");b=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(b);b=
KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(b);f=KUPLOADTOP.G_CURRKUPLOADER._config.maxOneFileSize;c=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileSize;a="";"020"==b.code?(a=RAONKUpload_Lang.message_limit_one_size,a=a.replace("{0}",KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(f).toString)):a="021"==b.code?RAONKUpload_Lang.message_file_ext_detect_html4:"022"==b.code?RAONKUpload_Lang.file_maximum+" "+KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(c).toString+RAONKUpload_Lang.message_limit_size:b.message;f=0;
if("020"==b.code||"021"==b.code||"022"==b.code){for(c=0;c<uploaders[upload_complete_count];c++)"y"==RESULTFILELIST[c].isDelete&&f++;var d=uploaders[upload_complete_count]-f;setSelectFile(d,0);d=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm;KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=1;KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID);KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=d}if("022"==
b.code)for(var n=RESULTFILELIST.length,c=uploaders[upload_complete_count];c<n;c++)"y"==RESULTFILELIST[c].isDelete?f++:"n"==RESULTFILELIST[c].isWebFile&&(d=c-f,setSelectFile(d,0),d=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm,KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=1,KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID),KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=d,c--,n--);h(b.code,
a)}}
function uploadProgress_html4(b,g,h){var a=getDialogDocument();adjustUploadFileListScroll(b-1,b,g);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[b]).style.width="0%";G_IntervalObj=setInterval(function(){f()},400);var f=function(){var f;f=0;if(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[b])){f=a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[b]).style.width.split("%");f=Math.round(1*f[0]*h/100);f++;if(f==parseInt(3*h/5,10)+1)c("1");else if(f==parseInt(4*h/5,10)+
1)c("2");else if(f==parseInt(9*h/10,10)+1)c("3");else if(f==parseInt(24*h/25,10)+1){c("4");return}if(1==f)if(a.getElementById("RAON_K_UP_upload_count"))a.getElementById("RAON_K_UP_upload_count").innerHTML=b+1+"/"+g;else return;var e=parseInt(1/h*100*f,10);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[b])&&(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[b]).style.width=e+"%",a.getElementById("RAON_K_UP_current_upload_progress_bar")&&(a.getElementById("RAON_K_UP_current_upload_progress_bar").style.width=
e+"%"),f=parseInt(1*b/g*100,10)+parseInt(parseInt(1/h*100*f,10)/g,10),a.getElementById("RAON_K_UP_total_upload_percent")&&(a.getElementById("RAON_K_UP_total_upload_percent").innerHTML=f+"%",a.getElementById("RAON_K_UP_total_upload_progress_bar")&&(a.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=f+"%",a.getElementById("RAON_K_UP_upload_size")&&0==PREVIOUSUPLOADEDSIZE&&(a.getElementById("RAON_K_UP_upload_size").innerHTML="-"))))}},c=function(a){"1"==a?(clearInterval(G_IntervalObj),
G_IntervalObj=setInterval(function(){f()},800)):"2"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){f()},1E3)):"3"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){f()},1200)):"4"==a&&clearInterval(G_IntervalObj)};null==KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval&&(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=setInterval(function(){a.getElementById("RAON_K_UP_process_time").innerHTML=viewTime(++KUPLOADTOP.G_CURRKUPLOADER.processTime)},1E3))}
function uploadProgressComplete_html4(b){var g=getDialogDocument(),h=uploaders[upload_complete_count];if(void 0!=h){var a=parseInt(1*(upload_complete_count+1)/TOTALUPLOADNUM*100,10);g.getElementById("RAON_K_UP_current_upload_progress_bar").style.width="100%";g.getElementById("RAON_K_UP_uploadFileProgress_"+h).style.width="100%";g.getElementById("RAON_K_UP_uploadFilePercent_"+h).style.color="";g.getElementById("RAON_K_UP_uploadFilePercent_"+h).innerHTML="100%";g.getElementById("RAON_K_UP_uploadFileSize_"+
h).innerHTML=b.toString;UPLOADIDX++;g.getElementById("RAON_K_UP_upload_count").innerHTML=upload_complete_count+1+"/"+TOTALUPLOADNUM;g.getElementById("RAON_K_UP_total_upload_percent").innerHTML=a+"%";g.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=a+"%";g.getElementById("RAON_K_UP_upload_size").innerHTML=KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(PREVIOUSUPLOADEDSIZE).toString;100==a&&(clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval),KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=
null,KUPLOADTOP.G_CURRKUPLOADER.processTime=0)}};
