(function(){try{var c={pluginName:"kmonitoring",transferId:"",transferSpeed:{recentSpeed:0,avgSpeed:0},transferPath:[],transferStartTime:[],transferCompleteTime:[],intervalProcess:"",bandwidth:0,zipDownloadGuid:"",downloadLISTLen:"",downloadIdxArr:[]};G_KUPlugin.kmonitoring=c;c.setTransferTime=function(c){var f,b=new Date;b.setHours(b.getHours()-9);f=""+b.getFullYear();var d=""+(b.getMonth()+1);1==d.length&&(d="0"+d);var a=""+b.getDate();1==a.length&&(a="0"+a);var k=""+b.getHours();1==k.length&&(k=
"0"+k);var l=""+b.getMinutes();1==l.length&&(l="0"+l);b=""+b.getSeconds();1==b.length&&(b="0"+b);f=f+"-"+d+"-"+a+" "+k+":"+l+":"+b;"start"==c?G_KUPlugin.kmonitoring.transferStartTime.push(f):G_KUPlugin.kmonitoring.transferCompleteTime.push(f)};c.dataReset=function(){clearInterval(c.intervalProcess);c.transferSpeed={recentSpeed:0,avgSpeed:0};c.transferPath=[];c.transferStartTime=[];c.transferCompleteTime=[];c.bandwidth=0;c.zipDownloadGuid="";c.downloadLISTLen=0;c.downloadIdxArr=[]};c.preUploadRequest=
function(n){var f="",b="",d="",a="",k="";c.transferId=(new Date).toISOString().substring(0,10)+"_"+KUPLOADTOP.RAONKUPLOAD.util.makeGuid();for(var l=0;l<uploaders.length;l++){var p="",p=KUPLOADTOP.G_CURRKUPLOADER.isCurrResumeUpload?KUPLOADTOP.G_CURRKUPLOADER.resumeInfoObj.guid:KUPLOADTOP.RAONKUPLOAD.util.makeGuid();RESULTFILELIST[l].guid=p;d+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[l].guid;a+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[l].originName;k+=KUPLOADTOP.RAONKSolution.Agent.backspace+
RESULTFILELIST[l].fileSize}var d=d.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,""),a=a.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,""),k=k.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,""),b=b+("kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c00"+KUPLOADTOP.RAONKSolution.Agent.vertical),b=b+("km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical),b=b+("km01"+KUPLOADTOP.RAONKSolution.Agent.formfeed+uploaders.length+KUPLOADTOP.RAONKSolution.Agent.vertical),
b=b+("km02"+KUPLOADTOP.RAONKSolution.Agent.formfeed+TOTALUPLOADSIZE+KUPLOADTOP.RAONKSolution.Agent.vertical),b=b+("km04"+KUPLOADTOP.RAONKSolution.Agent.formfeed+d+KUPLOADTOP.RAONKSolution.Agent.vertical),b=b+("km05"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical),b=b+("km06"+KUPLOADTOP.RAONKSolution.Agent.formfeed+k),g=KUPLOADTOP.RAONKUPLOAD.ajax.createXMLHttpRequest();g.onreadystatechange=function(){if(4==g.readyState)if(200==g.status){var a=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(g.responseText);
0==a.indexOf("[OK]")?(a=a.replace("[OK]",""),a=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(a),c.bandwidth=a.replace("Bandwidth|",""),changeBandwidth(c.bandwidth),n(),c.intervalProcess=setInterval(function(){c.processUpload()},1E3*parseInt(KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorPollingTime,10))):0==a.indexOf("[FAIL]")&&(a=a.replace("[FAIL]",""),a=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(a),a=KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(a),c.fn_sendError(null,g.status,a,
"preUploadRequest"),g=void 0)}else if(400<=g.status&&600>g.status||0==g.status)c.fn_sendError(null,g.status,"","preUploadRequest"),g=void 0};b=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(b);f+=b.name+"="+b.value;b=G_FormData.length;for(d=0;d<b;d++)a=G_FormData[d].form_value,a="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(a).value:encodeURIComponent(a),f+="&"+G_FormData[d].form_name+"="+a;g.open("POST",KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorUrl,
!0);g.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");try{g.send(f)}catch(e){c.fn_sendError(e,"","","preUploadRequest"),g=void 0}};c.processUpload=function(){var n="",f,b=c.transferSpeed.recentSpeed?c.transferSpeed.recentSpeed:0,d=c.transferSpeed.avgSpeed?c.transferSpeed.avgSpeed:0;f=""+("kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c01"+KUPLOADTOP.RAONKSolution.Agent.vertical);f+="km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical;
f+="km08"+KUPLOADTOP.RAONKSolution.Agent.formfeed+PREVIOUSUPLOADEDSIZE+KUPLOADTOP.RAONKSolution.Agent.vertical;f+="km13"+KUPLOADTOP.RAONKSolution.Agent.formfeed+d+"/"+b+"/"+c.bandwidth+KUPLOADTOP.RAONKSolution.Agent.vertical;f+="km14"+KUPLOADTOP.RAONKSolution.Agent.formfeed+upload_complete_count;var a=KUPLOADTOP.RAONKUPLOAD.ajax.createXMLHttpRequest();a.onreadystatechange=function(){if(4==a.readyState)if(200==a.status){var b=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(a.responseText);0==b.indexOf("[OK]")?
(b=b.replace("[OK]",""),b=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(b),c.bandwidth=b.replace("Bandwidth|","")):0==b.indexOf("[FAIL]")&&(clearInterval(c.intervalProcess),b=b.replace("[FAIL]",""),b=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(b),b=KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(b),c.fn_sendError(null,a.status,b,"processUpload"),a=void 0)}else if(400<=a.status&&600>a.status||0==a.status)c.fn_sendError(null,a.status,"","processUpload"),a=void 0};f=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(f);
n+=f.name+"="+f.value;a.open("POST",KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorPartUrl?KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorPartUrl:KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorUrl,!0);a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");try{a.send(n)}catch(k){c.fn_sendError(k,"","","processUpload"),a=void 0}};c.endUploadRequest=function(n,f){clearInterval(c.intervalProcess);var b="",d="",a="",k="",l="",p="",g="",e="";if("2"!=f&&"3"!=f||0!=KUPLOADTOP.G_CURRKUPLOADER.frameWin.upload_complete_count){for(var h=
0;h<uploaders.length;h++)"complete"==RESULTFILELIST[uploaders[h]].status&&(b+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[uploaders[h]].guid,d+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[uploaders[h]].fileSize,k+=KUPLOADTOP.RAONKSolution.Agent.backspace+(c.transferPath[uploaders[h]]?c.transferPath[h]:""),a+=KUPLOADTOP.RAONKSolution.Agent.backspace+(RESULTFILELIST[uploaders[h]].compress?"1":"0"),l+=KUPLOADTOP.RAONKSolution.Agent.backspace+(c.transferStartTime[h]?c.transferStartTime[h]:
""),p+=KUPLOADTOP.RAONKSolution.Agent.backspace+(c.transferCompleteTime[h]?c.transferCompleteTime[h]:""));b=b.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");d=d.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");k=k.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");a=a.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");l=l.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");p=p.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");c.fileId=b.split(KUPLOADTOP.RAONKSolution.Agent.backspace);
e+="kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c02"+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km04"+KUPLOADTOP.RAONKSolution.Agent.formfeed+b+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km06"+KUPLOADTOP.RAONKSolution.Agent.formfeed+d+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km07"+KUPLOADTOP.RAONKSolution.Agent.formfeed+k+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km09"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km10"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km11"+KUPLOADTOP.RAONKSolution.Agent.formfeed+n+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+f+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km15"+KUPLOADTOP.RAONKSolution.Agent.formfeed+l+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="km16"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
p}else e+="kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c02"+KUPLOADTOP.RAONKSolution.Agent.vertical,e+="km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical,e+="km09"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical,e+="km11"+KUPLOADTOP.RAONKSolution.Agent.formfeed+n+KUPLOADTOP.RAONKSolution.Agent.vertical,e+="km12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+f+KUPLOADTOP.RAONKSolution.Agent.vertical;
b=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(e);g+=b.name+"="+b.value;b=G_FormData.length;for(d=0;d<b;d++)a=G_FormData[d].form_value,a="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(a).value:encodeURIComponent(a),g+="&"+G_FormData[d].form_name+"="+a;var m=KUPLOADTOP.RAONKUPLOAD.ajax.createXMLHttpRequest();m.onreadystatechange=function(){if(4==m.readyState)if(200==m.status){c.dataReset();var a=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(m.responseText);
if(0==a.indexOf("[OK]")){for(a=0;a<uploaders.length;a++)RESULTFILELIST[uploaders[a]].fileId&&(RESULTFILELIST[uploaders[a]].fileId=c.fileId[a]),RESULTFILELIST[uploaders[a]].transferId&&(RESULTFILELIST[uploaders[a]].transferId=c.transferId);c.transferId="";c.fileId=""}else 0==a.indexOf("[FAIL]")&&(c.transferId="",c.fileId="",a=a.replace("[FAIL]",""),a=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(a),a=KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(a),c.fn_sendError(null,m.status,a,"endUploadRequest"),
m=void 0)}else if(400<=m.status&&600>m.status||0==m.status)c.fn_sendError(null,m.status,"","endUploadRequest"),m=void 0};m.open("POST",KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorUrl,!0);m.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");try{m.send(g)}catch(q){c.fn_sendError(q,"","","endUploadRequest"),m=void 0}};c.fn_sendError=function(n,f,b,d){try{"preUploadRequest"!=d&&"processUpload"!=d||!b?c.dataReset():c.endUploadRequest(b.code+"|"+b.message,"3");var a=getUploadedFileListObj(),
k="",l="",p="";b?(l=b.code,k=b.message):("preUploadRequest"==d?l="C005":"processUpload"==d?l="C009":"endUploadRequest"==d&&(l="C006"),n?k=n.message:void 0!=f&&(k="http(s) status is "+f),p=RAONKUpload_Lang.error_info["error_code_"+l]+"\n"+k);n={strType:"upload",strCode:l,strMessage:""==p?k:p,arrUploadedFileList:a};if("function"==typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.onError)KUPLOADTOP.G_CURRKUPLOADER._config.event.onError(KUPLOADTOP.G_CURRKUPLOADER.ID,n);else"function"!==typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError&&
alert("Error Code : "+n.strCode+"\nError Message : "+n.strMessage),KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError(KUPLOADTOP.G_CURRKUPLOADER.ID,n)}catch(g){}try{if(1==G_MultiTranferCheck)G_MultiTranferCheck=4;else try{"0"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile&&fileListReset()}catch(e){}0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()}catch(h){}};
c.preDownloadRequest=function(n,f){var b="",d="",a="",k="",l="";c.transferId=(new Date).toISOString().substring(0,10)+"_"+KUPLOADTOP.RAONKUPLOAD.util.makeGuid();var p=0;c.downloadLISTLen=n;c.downloadIdxArr=G_downloadIdxArr;if(1<n){a=KUPLOADTOP.RAONKUPLOAD.util.makeGuid();c.zipDownloadGuid=a;for(var k=KUPLOADTOP.G_CURRKUPLOADER._config.zipFileName,g=0;g<G_downloadIdxArr.length;g++)p+=RESULTFILELIST[G_downloadIdxArr[g]].fileSize;l=p}else{for(g=0;g<G_downloadIdxArr.length;g++)RESULTFILELIST[G_downloadIdxArr[g]].guid=
KUPLOADTOP.RAONKUPLOAD.util.makeGuid(),a+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[G_downloadIdxArr[g]].guid,k+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[G_downloadIdxArr[g]].originName,l+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[G_downloadIdxArr[g]].fileSize,p+=RESULTFILELIST[G_downloadIdxArr[g]].fileSize;a=a.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");k=k.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");l=l.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,
"")}d+="kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c10"+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="km01"+KUPLOADTOP.RAONKSolution.Agent.formfeed+(1<n?1:G_downloadIdxArr.length)+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="km02"+KUPLOADTOP.RAONKSolution.Agent.formfeed+p+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="km04"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical;
d+="km05"+KUPLOADTOP.RAONKSolution.Agent.formfeed+k+KUPLOADTOP.RAONKSolution.Agent.vertical;d+="km06"+KUPLOADTOP.RAONKSolution.Agent.formfeed+l;g=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(d);b+=g.name+"="+g.value;g=G_FormData.length;for(d=0;d<g;d++)a=G_FormData[d].form_value,a="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(a).value:encodeURIComponent(a),b+="&"+G_FormData[d].form_name+"="+a;d=KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorUrl;
if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useDownloadCache){a={list:[]};k=!1;for(g=0;g<G_downloadIdxArr.length;g++){if(RESULTFILELIST[G_downloadIdxArr[g]].cacheKey){k=!0;break}"1"==KUPLOADTOP.G_CURRKUPLOADER._config.downloadMulti&&a.list.push({url:KUPLOADTOP.G_CURRKUPLOADER._config.handlerUrl+"?cache_key="+RESULTFILELIST[G_downloadIdxArr[g]].customValue,cached:!1})}k||("0"==KUPLOADTOP.G_CURRKUPLOADER._config.downloadMulti&&a.list.push({url:KUPLOADTOP.G_CURRKUPLOADER._config.handlerUrl+"?cache_key=",
cached:!1}),b+="&fdn="+JSON.stringify(a),d+="?method=check_cache_status")}var e=KUPLOADTOP.RAONKUPLOAD.ajax.createXMLHttpRequest();e.onreadystatechange=function(){if(4==e.readyState)if(200==e.status){var a=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(e.responseText);0==a.indexOf("[OK]")?(a=a.replace("[OK]",""),a=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(a),c.bandwidth=a.replace("Bandwidth|",""),changeBandwidth(c.bandwidth),f(),c.intervalProcess=setInterval(function(){c.processDownload()},
1E3*parseInt(KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorPollingTime,10))):0==a.indexOf("[FAIL]")&&(a=a.replace("[FAIL]",""),a=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(a),a=KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(a),e=void 0)}else if(400<=e.status&&600>e.status||0==e.status)e=void 0};e.open("POST",d,!0);e.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");try{e.send(b)}catch(h){}};c.processDownload=function(){var n="",f,b=c.transferSpeed.recentSpeed?
c.transferSpeed.recentSpeed:0,d=c.transferSpeed.avgSpeed?c.transferSpeed.avgSpeed:0;f=""+("kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c11"+KUPLOADTOP.RAONKSolution.Agent.vertical);f+="km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical;f+="km08"+KUPLOADTOP.RAONKSolution.Agent.formfeed+PREVIOUSUPLOADEDSIZE+KUPLOADTOP.RAONKSolution.Agent.vertical;f+="km13"+KUPLOADTOP.RAONKSolution.Agent.formfeed+d+"/"+b+"/"+c.bandwidth+KUPLOADTOP.RAONKSolution.Agent.vertical;
f+="km14"+KUPLOADTOP.RAONKSolution.Agent.formfeed+upload_complete_count;var a=KUPLOADTOP.RAONKUPLOAD.ajax.createXMLHttpRequest();a.onreadystatechange=function(){if(4==a.readyState)if(200==a.status){var b=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(a.responseText);0==b.indexOf("[OK]")?(b=b.replace("[OK]",""),b=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(b),c.bandwidth=b.replace("Bandwidth|","")):0==b.indexOf("[FAIL]")&&(a=void 0)}else if(400<=a.status&&600>a.status||0==a.status)a=void 0};
f=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(f);n+=f.name+"="+f.value;a.open("POST",KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorPartUrl?KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorPartUrl:KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorUrl,!0);a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");try{a.send(n)}catch(k){a=void 0}};c.endDownloadRequest=function(n,f){clearInterval(c.intervalProcess);var b="",d="",a="",k="",l="",p="",g=0,e="",h="";if("2"!=f&&"3"!=f||0!=
KUPLOADTOP.G_CURRKUPLOADER.frameWin.upload_complete_count){if(1<c.downloadLISTLen){for(var b=c.zipDownloadGuid,m=0;m<c.downloadLISTLen;m++)g+=RESULTFILELIST[c.downloadIdxArr[m]].fileSize,k+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[c.downloadIdxArr[m]].webPath;d=g;k=k.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");a=RESULTFILELIST[c.downloadIdxArr[0]].compress?"1":"0";l=c.transferStartTime[0];p=c.transferCompleteTime[0]}else{for(m=0;m<c.downloadIdxArr.length;m++)"complete"==RESULTFILELIST[c.downloadIdxArr[m]].status&&
(b+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[c.downloadIdxArr[m]].guid,d+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[c.downloadIdxArr[m]].fileSize,k+=KUPLOADTOP.RAONKSolution.Agent.backspace+RESULTFILELIST[c.downloadIdxArr[m]].webPath,a+=KUPLOADTOP.RAONKSolution.Agent.backspace+(RESULTFILELIST[c.downloadIdxArr[m]].compress?"1":"0"),l+=KUPLOADTOP.RAONKSolution.Agent.backspace+c.transferStartTime[m],p+=KUPLOADTOP.RAONKSolution.Agent.backspace+c.transferCompleteTime[m]);b=
b.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");d=d.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");k=k.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");a=a.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");l=l.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"");p=p.replace(KUPLOADTOP.RAONKSolution.Agent.backspace,"")}h+="kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c12"+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical;
h+="km04"+KUPLOADTOP.RAONKSolution.Agent.formfeed+b+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km06"+KUPLOADTOP.RAONKSolution.Agent.formfeed+d+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km07"+KUPLOADTOP.RAONKSolution.Agent.formfeed+k+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km09"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km10"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical;
h+="km11"+KUPLOADTOP.RAONKSolution.Agent.formfeed+n+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+f+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km15"+KUPLOADTOP.RAONKSolution.Agent.formfeed+l+KUPLOADTOP.RAONKSolution.Agent.vertical;h+="km16"+KUPLOADTOP.RAONKSolution.Agent.formfeed+p}else h+="kmc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c12"+KUPLOADTOP.RAONKSolution.Agent.vertical,h+="km00"+KUPLOADTOP.RAONKSolution.Agent.formfeed+c.transferId+KUPLOADTOP.RAONKSolution.Agent.vertical,
h+="km09"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical,h+="km11"+KUPLOADTOP.RAONKSolution.Agent.formfeed+n+KUPLOADTOP.RAONKSolution.Agent.vertical,h+="km12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+f+KUPLOADTOP.RAONKSolution.Agent.vertical;b=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(h);e+=b.name+"="+b.value;b=G_FormData.length;for(d=0;d<b;d++)a=G_FormData[d].form_value,a="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?
KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(a).value:encodeURIComponent(a),e+="&"+G_FormData[d].form_name+"="+a;var q=KUPLOADTOP.RAONKUPLOAD.ajax.createXMLHttpRequest();q.onreadystatechange=function(){if(4==q.readyState)if(200==q.status){c.dataReset();var a=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(q.responseText);0!=a.indexOf("[OK]")&&0==a.indexOf("[FAIL]")&&(q=void 0)}else if(400<=q.status&&600>q.status||0==q.status)q=void 0};q.open("POST",KUPLOADTOP.G_CURRKUPLOADER._config.kMonitorUrl,
!0);q.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");try{q.send(e)}catch(r){q=void 0}}}catch(r){}})();
